#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Pre-results DOD report plots/tables for reviewed mIF prep roots.

This script audits the actual labels written into each ATHENA/1NN prep root and
creates report-friendly plots/tables for:

1) Mean cell-count composition in epithelial/tumor vs stroma regions.
2) Abundance-vs-consistency bubble plots for each prep root and panel.
3) Cohort-proportional heatmaps for final prep-root labels.
4) Cohort-proportional heatmaps for raw marker combinations from cell_df parquets.
5) Supplementary CSV tables summarizing labels, marker combinations, and valid units.

Report scope by default excludes NAC2015 and KOLL, and keeps:
    NAC2020, PURE01, No-NAC, BLASST

QC handling:
    - TMA cohorts: retain only source-complete units with structural_acceptability
      in Acceptable/Borderline by default.
    - BLASST: retain source-complete whole-section regions; manual TMA-style
      structural review is not expected.

Expected prep roots generated by submit.sh:
    /projects/ovcare/users/nikolay_alabi/immuno/weibull/run_reviewed_phenotype_only
    /projects/ovcare/users/nikolay_alabi/immuno/weibull/run_reviewed_AR_state
    /projects/ovcare/users/nikolay_alabi/immuno/weibull/run_reviewed_AR_checkpoint_state
    /projects/ovcare/users/nikolay_alabi/immuno/weibull/run_reviewed_compartment
    /projects/ovcare/users/nikolay_alabi/immuno/weibull/run_reviewed_compartment_state

Each prep chunk should contain 1NN_prep.tsv, as written by prep_inputs.py.
"""

from __future__ import annotations

import argparse
import math
import re
from pathlib import Path
from typing import Dict, Iterable, Optional

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.patches import Patch


# -----------------------------------------------------------------------------
# Defaults
# -----------------------------------------------------------------------------

REPORT_COHORTS = ["NAC2020", "PURE01", "No-NAC", "BLASST"]
REPORT_COHORTS_NO_BLASST = ["NAC2020", "PURE01", "No-NAC"]
PANEL_ORDER = ["AR", "BT"]
SAMPLE_TYPE_ORDER = ["TURBT", "RC"]
REGION_ORDER = ["Epi", "Stroma"]

DEFAULT_WEIBULL_ROOT = Path("/projects/ovcare/users/nikolay_alabi/immuno/weibull")
DEFAULT_QC_DIR = Path("/projects/ovcare/users/nikolay_alabi/immuno/data/qc_check_rebuild")
DEFAULT_CELL_DIR = Path("/projects/ovcare/users/nikolay_alabi/immuno/phenotype_assignments/cell_df_rebuild")
DEFAULT_OUT_DIR = Path("/projects/ovcare/users/nikolay_alabi/immuno/manuscript/dod_report/figure_outputs/prep_root_label_audit")

DEFAULT_PREP_ROOTS = {
    "phenotype_only": "run_reviewed_phenotype_only",
    "AR_state": "run_reviewed_AR_state",
    "AR_checkpoint_state": "run_reviewed_AR_checkpoint_state",
    "compartment": "run_reviewed_compartment",
    "compartment_state": "run_reviewed_compartment_state",
}

EXCLUDED_BASE_LABELS = {
    "artifact",
    "unresolved",
    "mixed_lineage",
    "mixed-lineage",
    "mixed lineage",
    "unknown",
    "nan",
    "none",
    "",
}

# Slightly opinionated color palette for common final labels. Unknown labels are
# assigned automatically by matplotlib. Red is reserved for excluded/non-primary.
BASE_LABEL_COLORS = {
    "ALL_NEG": "#1f77b4",
    "stroma": "#ff7f0e",
    "tumor": "#2ca02c",
    "tumour": "#2ca02c",
    "t_cell": "#ffbb78",
    "cd8_t_cell": "#9467bd",
    "macrophage": "#8c564b",
    "b_cell": "#17becf",
    "plasma_cell": "#bcbd22",
    "treg_cell": "#e377c2",
    "immune": "#7f7f7f",
    "checkpoint_neg": "#1f77b4",
    "PD1": "#9467bd",
    "PDL1": "#8c564b",
    "PD1_PDL1": "#d62728",
    "artifact": "#d62728",
    "unresolved": "#d62728",
    "mixed_lineage": "#d62728",
}


# -----------------------------------------------------------------------------
# Normalization helpers
# -----------------------------------------------------------------------------

def norm_str(x) -> str:
    if pd.isna(x):
        return ""
    return re.sub(r"\s+", " ", str(x)).strip()


def normalize_panel(x) -> str:
    s = norm_str(x).upper()
    if s in {"AR", "ARP"}:
        return "AR"
    if s in {"BT", "B&T", "B+T", "B_T", "B T"}:
        return "BT"
    if s in {"MY", "M", "MYELOID"}:
        return "MY"
    return norm_str(x)


def normalize_cohort(x) -> str:
    s = norm_str(x)
    su = s.upper().replace("_", " ").replace("-", "")
    if su in {"BCA2020", "BCA 2020", "NAC2020"}:
        return "NAC2020"
    if su in {"NONAC", "NO NAC"}:
        return "No-NAC"
    if su == "PURE01":
        return "PURE01"
    if su == "BLASST":
        return "BLASST"
    if su == "NAC2015" or su.startswith("BLADDER"):
        return "NAC2015"
    if su in {"KOLL", "FLORESTAN"}:
        return "KOLL"
    return s


def normalize_sample_type(x) -> str:
    s = norm_str(x).upper()
    if "TURBT" in s:
        return "TURBT"
    if s == "RC" or "CYSTECTOMY" in s:
        return "RC"
    return norm_str(x) if norm_str(x) else "Unknown"


def normalize_qc(x) -> str:
    s = norm_str(x)
    if s == "" or s.lower() in {"nan", "none", "na", "<na>", "unknown"}:
        return "Missing QC"
    sl = s.lower()
    if sl in {"acceptable", "accepted", "accept", "good", "pass", "usable"}:
        return "Acceptable"
    if sl in {"borderline", "borderline usable", "borderline/usable"}:
        return "Borderline"
    if sl in {"unusable", "fail", "failed", "bad", "reject", "rejected"}:
        return "Unusable"
    return s


def normalize_region_from_prep(assigned_loc, tumor_stroma=None) -> str:
    """Convert prep region labels to Epi/Stroma/Other."""
    s = norm_str(assigned_loc).lower()
    t = norm_str(tumor_stroma).lower()
    if s in {"epithelial", "epi", "tumor", "tumour"} or t in {"tumor", "tumour", "epi", "epithelial"}:
        return "Epi"
    if s in {"stroma", "str"} or t in {"stroma", "str"}:
        return "Stroma"
    return "Other"


def base_label(label: str) -> str:
    """Return base label before checkpoint-state suffix."""
    s = norm_str(label)
    if "__" in s:
        return s.split("__", 1)[0]
    return s


def is_excluded_label(label: str) -> bool:
    """Heuristic flag for labels excluded from primary analysis."""
    s = norm_str(label).lower()
    b = base_label(s).lower()
    if b in EXCLUDED_BASE_LABELS or s in EXCLUDED_BASE_LABELS:
        return True
    if any(tok in s for tok in ["artifact", "unresolved", "mixed_lineage", "mixed-lineage", "mixed lineage"]):
        return True
    return False


def safe_filename(x: str) -> str:
    x = norm_str(x)
    x = re.sub(r"[^A-Za-z0-9._-]+", "_", x)
    x = re.sub(r"_+", "_", x).strip("_")
    return x or "NA"


# -----------------------------------------------------------------------------
# QC / valid-unit loading
# -----------------------------------------------------------------------------

def load_valid_units(
    qc_dir: Path = DEFAULT_QC_DIR,
    cohorts: list[str] | None = None,
    panels: list[str] | None = None,
    keep_qc_statuses: list[str] | None = None,
    require_all_primary_inputs: bool = True,
) -> pd.DataFrame:
    """Load source_presence_all.csv and return valid coord/panel/cohort units."""
    cohorts = cohorts or REPORT_COHORTS
    panels = panels or PANEL_ORDER
    keep_qc_statuses = keep_qc_statuses or ["Acceptable", "Borderline"]

    fp = qc_dir / "source_presence_all.csv"
    if not fp.exists():
        raise FileNotFoundError(f"Missing QC source-presence file: {fp}")

    d = pd.read_csv(fp, low_memory=False)
    for c in ["branch", "panel", "cohort_label", "sample_type", "coord"]:
        if c not in d.columns:
            d[c] = pd.NA

    d["panel"] = d["panel"].map(normalize_panel)
    d["cohort"] = d["cohort_label"].map(normalize_cohort)
    d["sample_type"] = d["sample_type"].map(normalize_sample_type)
    d["qc_status"] = d.get("structural_acceptability", pd.Series(pd.NA, index=d.index)).map(normalize_qc)

    d = d[d["cohort"].isin(cohorts)].copy()
    d = d[d["panel"].isin(panels)].copy()
    d = d[d["coord"].notna()].copy()

    if require_all_primary_inputs and "has_all_primary_inputs" in d.columns:
        d["has_all_primary_inputs"] = d["has_all_primary_inputs"].fillna(False).astype(bool)
        d = d[d["has_all_primary_inputs"]].copy()

    is_tma = d["branch"].astype(str).eq("TMA")
    d = d[(~is_tma) | (is_tma & d["qc_status"].isin(keep_qc_statuses))].copy()

    keep = [
        "branch", "panel", "cohort", "sample_type", "coord", "qc_status",
        "has_all_primary_inputs", "n_parquet_cells", "entity_id",
    ]
    keep = [c for c in keep if c in d.columns]
    out = d[keep].drop_duplicates(["panel", "cohort", "coord"]).copy()
    out["unit_key"] = out["panel"].astype(str) + "|" + out["cohort"].astype(str) + "|" + out["coord"].astype(str)
    return out.reset_index(drop=True)


# -----------------------------------------------------------------------------
# Prep-root aggregation
# -----------------------------------------------------------------------------

def prep_root_paths(weibull_root: Path = DEFAULT_WEIBULL_ROOT, prep_roots: Optional[dict[str, str]] = None) -> dict[str, Path]:
    prep_roots = prep_roots or DEFAULT_PREP_ROOTS
    return {name: (weibull_root / subdir) for name, subdir in prep_roots.items()}


def iter_1nn_files(root: Path):
    yield from sorted(root.rglob("1NN_prep.tsv"))


def read_1nn_counts_for_root(root_name: str, root: Path) -> pd.DataFrame:
    """Aggregate all 1NN_prep.tsv chunks to unit/region/label counts."""
    files = list(iter_1nn_files(root))
    if not files:
        print(f"[WARN] No 1NN_prep.tsv files found under {root}")
        return pd.DataFrame()

    usecols = ["sample_id", "coord", "Panel", "cohort", "phenotype", "assigned_loc", "tumor_stroma"]
    parts = []

    for i, fp in enumerate(files, 1):
        try:
            chunk = pd.read_csv(fp, sep="\t", usecols=lambda c: c in usecols, low_memory=False)
        except Exception as e:
            print(f"[WARN] Failed reading {fp}: {e}")
            continue

        required = ["sample_id", "coord", "Panel", "cohort", "phenotype"]
        missing = [c for c in required if c not in chunk.columns]
        if missing:
            print(f"[WARN] Skipping {fp}; missing columns: {missing}")
            continue

        if "assigned_loc" not in chunk.columns:
            chunk["assigned_loc"] = pd.NA
        if "tumor_stroma" not in chunk.columns:
            chunk["tumor_stroma"] = pd.NA

        chunk["prep_root"] = root_name
        chunk["panel"] = chunk["Panel"].map(normalize_panel)
        chunk["cohort"] = chunk["cohort"].map(normalize_cohort)
        chunk["label"] = chunk["phenotype"].astype(str).str.strip()
        chunk["region_class"] = [
            normalize_region_from_prep(a, t)
            for a, t in zip(chunk["assigned_loc"], chunk["tumor_stroma"])
        ]
        chunk["coord"] = chunk["coord"].astype(str).str.strip()
        chunk["sample_id"] = chunk["sample_id"].astype(str).str.strip()
        chunk["unit_key"] = chunk["panel"].astype(str) + "|" + chunk["cohort"].astype(str) + "|" + chunk["coord"].astype(str)

        g = (
            chunk.groupby(["prep_root", "panel", "cohort", "coord", "unit_key", "sample_id", "region_class", "label"], dropna=False)
            .size()
            .reset_index(name="n_cells")
        )
        parts.append(g)

        if i % 25 == 0:
            print(f"[INFO] {root_name}: processed {i}/{len(files)} chunks")

    if not parts:
        return pd.DataFrame()

    out = pd.concat(parts, ignore_index=True)
    out = (
        out.groupby(["prep_root", "panel", "cohort", "coord", "unit_key", "sample_id", "region_class", "label"], dropna=False)["n_cells"]
        .sum()
        .reset_index()
    )
    out["label_base"] = out["label"].map(base_label)
    out["excluded_from_primary"] = out["label"].map(is_excluded_label)
    return out


def load_all_prep_counts(
    weibull_root: Path = DEFAULT_WEIBULL_ROOT,
    prep_roots: Optional[dict[str, str]] = None,
    valid_units: Optional[pd.DataFrame] = None,
) -> pd.DataFrame:
    """Load/aggregate all configured prep roots and apply valid-unit filter."""
    paths = prep_root_paths(weibull_root, prep_roots)
    parts = []
    for root_name, root in paths.items():
        print(f"\n[LOAD] {root_name}: {root}")
        df = read_1nn_counts_for_root(root_name, root)
        if df.empty:
            continue
        parts.append(df)

    if not parts:
        raise ValueError("No prep-root counts could be loaded.")

    counts = pd.concat(parts, ignore_index=True)

    if valid_units is not None and not valid_units.empty:
        meta = valid_units[["unit_key", "sample_type", "branch", "qc_status"]].drop_duplicates("unit_key")
        counts = counts.merge(meta, on="unit_key", how="inner")
    else:
        counts["sample_type"] = "Unknown"
        counts["branch"] = pd.NA
        counts["qc_status"] = pd.NA

    counts = counts[counts["cohort"].isin(REPORT_COHORTS)].copy()
    counts = counts[counts["panel"].isin(PANEL_ORDER)].copy()
    counts = counts[counts["region_class"].isin(REGION_ORDER)].copy()

    return counts.reset_index(drop=True)


# -----------------------------------------------------------------------------
# Summary table builders
# -----------------------------------------------------------------------------

def make_valid_unit_summary(valid_units: pd.DataFrame) -> pd.DataFrame:
    return (
        valid_units.groupby(["cohort", "sample_type", "panel", "branch", "qc_status"], dropna=False)
        .agg(n_units=("unit_key", "nunique"), n_cells_qc=("n_parquet_cells", "sum"))
        .reset_index()
        .sort_values(["cohort", "sample_type", "panel", "branch", "qc_status"])
    )


def make_label_summary(counts: pd.DataFrame) -> pd.DataFrame:
    """Across all included cohorts for each prep root/panel/label."""
    unit_totals = (
        counts.groupby(["prep_root", "panel", "unit_key"], dropna=False)["n_cells"]
        .sum()
        .reset_index(name="unit_total_cells")
    )
    label_unit = (
        counts.groupby(["prep_root", "panel", "label", "label_base", "excluded_from_primary", "unit_key"], dropna=False)["n_cells"]
        .sum()
        .reset_index()
        .merge(unit_totals, on=["prep_root", "panel", "unit_key"], how="left")
    )
    label_unit["unit_fraction"] = label_unit["n_cells"] / label_unit["unit_total_cells"].replace(0, np.nan)

    total_units = unit_totals.groupby(["prep_root", "panel"], dropna=False)["unit_key"].nunique().reset_index(name="n_units_total")

    summary = (
        label_unit.groupby(["prep_root", "panel", "label", "label_base", "excluded_from_primary"], dropna=False)
        .agg(
            n_cells=("n_cells", "sum"),
            n_units_present=("unit_key", "nunique"),
            median_fraction_when_present=("unit_fraction", "median"),
            mean_fraction_when_present=("unit_fraction", "mean"),
            max_fraction_when_present=("unit_fraction", "max"),
        )
        .reset_index()
        .merge(total_units, on=["prep_root", "panel"], how="left")
    )
    summary["fraction_units_present"] = summary["n_units_present"] / summary["n_units_total"].replace(0, np.nan)
    return summary.sort_values(["prep_root", "panel", "n_cells"], ascending=[True, True, False]).reset_index(drop=True)


def make_label_by_cohort_summary(counts: pd.DataFrame) -> pd.DataFrame:
    total = (
        counts.groupby(["prep_root", "panel", "cohort", "sample_type"], dropna=False)["n_cells"]
        .sum()
        .reset_index(name="total_cells")
    )
    g = (
        counts.groupby(["prep_root", "panel", "cohort", "sample_type", "label", "label_base", "excluded_from_primary"], dropna=False)["n_cells"]
        .sum()
        .reset_index()
        .merge(total, on=["prep_root", "panel", "cohort", "sample_type"], how="left")
    )
    g["cell_fraction"] = g["n_cells"] / g["total_cells"].replace(0, np.nan)
    return g.sort_values(["prep_root", "panel", "cohort", "sample_type", "n_cells"], ascending=[True, True, True, True, False]).reset_index(drop=True)


def make_mean_composition_summary(counts: pd.DataFrame) -> pd.DataFrame:
    """Mean cells per unit for each label within cohort/sample/region groups."""
    group_cols = ["prep_root", "panel", "cohort", "sample_type", "region_class"]
    units = (
        counts.groupby(group_cols + ["unit_key"], dropna=False)["n_cells"]
        .sum()
        .reset_index()
        .groupby(group_cols, dropna=False)["unit_key"]
        .nunique()
        .reset_index(name="n_units")
    )
    totals = (
        counts.groupby(group_cols + ["label", "label_base", "excluded_from_primary"], dropna=False)["n_cells"]
        .sum()
        .reset_index()
        .merge(units, on=group_cols, how="left")
    )
    totals["mean_cells_per_unit"] = totals["n_cells"] / totals["n_units"].replace(0, np.nan)
    return totals.sort_values(group_cols + ["n_cells"], ascending=[True, True, True, True, True, False]).reset_index(drop=True)


# -----------------------------------------------------------------------------
# Raw marker-combination summaries from cell_df parquets
# -----------------------------------------------------------------------------

def load_cell_df_counts(
    cell_dir: Path = DEFAULT_CELL_DIR,
    valid_units: Optional[pd.DataFrame] = None,
    include_whole: bool = True,
) -> pd.DataFrame:
    files = [cell_dir / "tma_cell_df.parquet"]
    if include_whole:
        files.append(cell_dir / "wholesection_cell_df.parquet")

    parts = []
    cols_wanted = [
        "sample_name", "coord", "Panel", "cohort", "marker_combination",
        "phenotype", "phenotype_canonical", "collapse_label", "state", "tissue_region",
    ]

    for fp in files:
        if not fp.exists():
            print(f"[WARN] Missing cell_df parquet: {fp}")
            continue
        try:
            import pyarrow.parquet as pq
            available_cols = set(pq.read_schema(fp).names)
            keep = [c for c in cols_wanted if c in available_cols]
            df = pd.read_parquet(fp, columns=keep)
        except Exception:
            # Fall back to reading the full parquet if schema inspection fails.
            df0 = pd.read_parquet(fp)
            keep = [c for c in cols_wanted if c in df0.columns]
            df = df0[keep].copy()
            del df0

        for c in ["coord", "Panel", "cohort"]:
            if c not in df.columns:
                raise ValueError(f"{fp} missing required column: {c}")
        df["panel"] = df["Panel"].map(normalize_panel)
        df["cohort"] = df["cohort"].map(normalize_cohort)
        df["coord"] = df["coord"].astype(str).str.strip()
        df["unit_key"] = df["panel"].astype(str) + "|" + df["cohort"].astype(str) + "|" + df["coord"].astype(str)

        if "marker_combination" in df.columns:
            df["marker_combo"] = df["marker_combination"].fillna("ALL_NEG").astype(str).str.strip()
        elif "phenotype_canonical" in df.columns:
            df["marker_combo"] = df["phenotype_canonical"].fillna("ALL_NEG").astype(str).str.strip()
        elif "phenotype" in df.columns:
            df["marker_combo"] = df["phenotype"].fillna("ALL_NEG").astype(str).str.strip()
        else:
            df["marker_combo"] = "Unknown"

        if "collapse_label" not in df.columns:
            df["collapse_label"] = "Unknown"
        if "state" not in df.columns:
            df["state"] = pd.NA

        df["collapse_label"] = df["collapse_label"].astype(str).str.strip()
        df["excluded_from_primary"] = df["collapse_label"].map(is_excluded_label)
        parts.append(df[["unit_key", "panel", "cohort", "coord", "marker_combo", "collapse_label", "state", "excluded_from_primary"]].copy())

    if not parts:
        return pd.DataFrame()

    out = pd.concat(parts, ignore_index=True)
    out = out[out["cohort"].isin(REPORT_COHORTS)].copy()
    out = out[out["panel"].isin(PANEL_ORDER)].copy()

    if valid_units is not None and not valid_units.empty:
        meta = valid_units[["unit_key", "sample_type", "branch", "qc_status"]].drop_duplicates("unit_key")
        out = out.merge(meta, on="unit_key", how="inner")
    else:
        out["sample_type"] = "Unknown"
        out["branch"] = pd.NA
        out["qc_status"] = pd.NA

    g = (
        out.groupby(["panel", "cohort", "sample_type", "marker_combo", "collapse_label", "state", "excluded_from_primary"], dropna=False)
        .size()
        .reset_index(name="n_cells")
    )
    totals = g.groupby(["panel", "cohort"], dropna=False)["n_cells"].sum().reset_index(name="total_cells_panel_cohort")
    g = g.merge(totals, on=["panel", "cohort"], how="left")
    g["cell_fraction_within_panel_cohort"] = g["n_cells"] / g["total_cells_panel_cohort"].replace(0, np.nan)
    return g.sort_values(["panel", "cohort", "n_cells"], ascending=[True, True, False]).reset_index(drop=True)


# -----------------------------------------------------------------------------
# Plotting helpers
# -----------------------------------------------------------------------------

def label_color_map(labels: Iterable[str], excluded_flags: Optional[dict[str, bool]] = None) -> dict[str, str]:
    labels = list(labels)
    cmap = plt.get_cmap("tab20")
    out = {}
    i = 0
    for lab in labels:
        if excluded_flags and excluded_flags.get(lab, False):
            out[lab] = "#d62728"
        else:
            b = base_label(lab)
            out[lab] = BASE_LABEL_COLORS.get(lab, BASE_LABEL_COLORS.get(b, cmap(i % 20)))
            i += 1
    return out


def maybe_group_minor_labels(df: pd.DataFrame, value_col: str, label_col: str = "label", max_labels: int = 25) -> pd.DataFrame:
    """Group small labels into 'Other labels' for stacked bar readability."""
    totals = df.groupby(label_col, dropna=False)[value_col].sum().sort_values(ascending=False)
    keep = set(totals.head(max_labels).index.astype(str))
    out = df.copy()
    out[label_col] = out[label_col].astype(str)
    out.loc[~out[label_col].isin(keep), label_col] = "Other labels"
    return out


def plot_mean_cell_count_composition(
    comp: pd.DataFrame,
    prep_root: str,
    panel: str,
    out_dir: Path,
    cohorts: list[str],
    prefix: str,
    max_stacked_labels: int = 25,
):
    sub = comp[(comp["prep_root"].eq(prep_root)) & (comp["panel"].eq(panel)) & (comp["cohort"].isin(cohorts))].copy()
    if sub.empty:
        return None

    sub = sub[sub["region_class"].isin(REGION_ORDER)].copy()
    sub["cohort"] = pd.Categorical(sub["cohort"], categories=cohorts, ordered=True)
    sub["sample_type"] = pd.Categorical(sub["sample_type"], categories=SAMPLE_TYPE_ORDER, ordered=True)
    sub["region_class"] = pd.Categorical(sub["region_class"], categories=REGION_ORDER, ordered=True)

    plot_df = maybe_group_minor_labels(sub, "mean_cells_per_unit", max_labels=max_stacked_labels)
    plot_df = (
        plot_df.groupby(["cohort", "sample_type", "region_class", "label"], observed=False, dropna=False)["mean_cells_per_unit"]
        .sum()
        .reset_index()
    )

    x_df = plot_df[["cohort", "sample_type", "region_class"]].drop_duplicates().sort_values(["cohort", "sample_type", "region_class"])
    x_df = x_df[(x_df["cohort"].isin(cohorts)) & (x_df["sample_type"].isin(SAMPLE_TYPE_ORDER)) & (x_df["region_class"].isin(REGION_ORDER))]
    x_df = x_df.reset_index(drop=True)
    x_df["x"] = np.arange(len(x_df))
    plot_df = plot_df.merge(x_df, on=["cohort", "sample_type", "region_class"], how="inner")

    labels = plot_df.groupby("label")["mean_cells_per_unit"].sum().sort_values(ascending=False).index.tolist()
    excl = {lab: is_excluded_label(lab) for lab in labels}
    colors = label_color_map(labels, excl)

    fig_w = max(12, 0.42 * len(x_df) + 4)
    fig, ax = plt.subplots(figsize=(fig_w, 5.2))
    bottom = np.zeros(len(x_df))

    for lab in labels:
        vals = (
            plot_df[plot_df["label"].eq(lab)]
            .set_index("x")["mean_cells_per_unit"]
            .reindex(x_df["x"].values)
            .fillna(0)
            .to_numpy()
        )
        ax.bar(x_df["x"], vals, bottom=bottom, label=lab, color=colors[lab], edgecolor="black", linewidth=0.2)
        bottom += vals

    tick_labels = [f"{r.cohort}\n{r.sample_type}\n{r.region_class}" for r in x_df.itertuples(index=False)]
    ax.set_xticks(x_df["x"])
    ax.set_xticklabels(tick_labels, rotation=55, ha="right", fontsize=8)
    ax.set_ylabel("Mean cells per core/image/region")
    ax.set_title(f"{prep_root} — {panel}: mean cell-count composition in Epi vs Stroma")
    ax.grid(axis="y", alpha=0.25)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)

    # Vertical separators between cohorts.
    for cohort in cohorts[:-1]:
        idx = x_df.index[x_df["cohort"].astype(str).eq(cohort)]
        if len(idx):
            ax.axvline(idx.max() + 0.5, color="black", linewidth=0.6, alpha=0.35)

    ax.legend(title="Final label", bbox_to_anchor=(1.02, 1), loc="upper left", fontsize=7, frameon=True)
    fig.tight_layout()

    out_dir.mkdir(parents=True, exist_ok=True)
    stem = f"{prefix}_{safe_filename(prep_root)}_{panel}_mean_cell_count_composition"
    fig.savefig(out_dir / f"{stem}.pdf", bbox_inches="tight")
    fig.savefig(out_dir / f"{stem}.png", dpi=300, bbox_inches="tight")
    plt.close(fig)
    return out_dir / f"{stem}.png"


def plot_abundance_consistency(
    label_summary: pd.DataFrame,
    prep_root: str,
    panel: str,
    out_dir: Path,
    include_blasst: bool,
    counts: pd.DataFrame,
    prefix: str,
    annotate_top_n: int = 30,
):
    cohorts = REPORT_COHORTS if include_blasst else REPORT_COHORTS_NO_BLASST
    sub_counts = counts[
        counts["prep_root"].eq(prep_root)
        & counts["panel"].eq(panel)
        & counts["cohort"].isin(cohorts)
    ].copy()
    if sub_counts.empty:
        return None

    sub_summary = make_label_summary(sub_counts)
    if sub_summary.empty:
        return None

    x = sub_summary["fraction_units_present"].clip(lower=1e-9)
    y = sub_summary["median_fraction_when_present"].clip(lower=1e-8)
    sizes = np.sqrt(sub_summary["n_cells"].astype(float))
    sizes = 30 + 2400 * (sizes / sizes.max())
    colors = np.where(sub_summary["excluded_from_primary"], "#d62728", "#1f77b4")

    fig, ax = plt.subplots(figsize=(9.5, 6.2))
    ax.scatter(x, y, s=sizes, c=colors, alpha=0.75, edgecolor="black", linewidth=0.5)
    ax.set_yscale("log")
    ax.set_xlim(-0.03, 1.03)
    ax.set_xlabel("Fraction of cores/regions where label appears")
    ax.set_ylabel("Median cell fraction within positive cores/regions")
    suffix = "with BLASST" if include_blasst else "without BLASST"
    ax.set_title(f"Abundance vs consistency — {prep_root}, panel={panel} ({suffix})")
    ax.grid(alpha=0.25)

    ann = sub_summary.sort_values("n_cells", ascending=False).head(annotate_top_n)
    for row in ann.itertuples(index=False):
        ax.text(row.fraction_units_present, max(row.median_fraction_when_present, 1e-8), str(row.label), fontsize=7)

    handles = [
        Patch(facecolor="#1f77b4", edgecolor="black", label="Primary/included label"),
        Patch(facecolor="#d62728", edgecolor="black", label="Excluded/non-primary label"),
    ]
    ax.legend(handles=handles, loc="lower right", frameon=True)
    fig.tight_layout()

    out_dir.mkdir(parents=True, exist_ok=True)
    stem = f"{prefix}_{safe_filename(prep_root)}_{panel}_abundance_consistency_{'withBLASST' if include_blasst else 'noBLASST'}"
    fig.savefig(out_dir / f"{stem}.pdf", bbox_inches="tight")
    fig.savefig(out_dir / f"{stem}.png", dpi=300, bbox_inches="tight")
    sub_summary.to_csv(out_dir / f"{stem}.source_data.csv", index=False)
    plt.close(fig)
    return out_dir / f"{stem}.png"


def plot_heatmap_matrix(
    mat: pd.DataFrame,
    title: str,
    out_prefix: Path,
    value_label: str = "Cell fraction",
    cmap: str = "viridis",
):
    if mat.empty:
        return None
    fig_h = max(4.5, 0.22 * mat.shape[0] + 1.5)
    fig_w = max(6.5, 1.1 * mat.shape[1] + 2.5)
    fig, ax = plt.subplots(figsize=(fig_w, fig_h))
    im = ax.imshow(mat.values, aspect="auto", interpolation="nearest", cmap=cmap)
    ax.set_xticks(np.arange(mat.shape[1]))
    ax.set_xticklabels(mat.columns, rotation=45, ha="right")
    ax.set_yticks(np.arange(mat.shape[0]))
    ax.set_yticklabels(mat.index, fontsize=7)
    ax.set_title(title)
    cb = fig.colorbar(im, ax=ax, fraction=0.035, pad=0.02)
    cb.set_label(value_label)
    fig.tight_layout()
    out_prefix.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(str(out_prefix) + ".pdf", bbox_inches="tight")
    fig.savefig(str(out_prefix) + ".png", dpi=300, bbox_inches="tight")
    mat.to_csv(str(out_prefix) + ".source_data.csv")
    plt.close(fig)
    return str(out_prefix) + ".png"


def plot_label_proportion_heatmaps(
    counts: pd.DataFrame,
    out_dir: Path,
    prefix: str,
    top_n: int = 40,
):
    outputs = []
    by_cohort = make_label_by_cohort_summary(counts)
    # Aggregate TURBT/RC together for the cohort-proportional heatmap, as requested.
    total_by_context = (
        by_cohort.groupby(["prep_root", "panel", "cohort", "label", "excluded_from_primary"], dropna=False)["n_cells"]
        .sum()
        .reset_index()
    )
    totals = total_by_context.groupby(["prep_root", "panel", "cohort"], dropna=False)["n_cells"].sum().reset_index(name="total_cells")
    total_by_context = total_by_context.merge(totals, on=["prep_root", "panel", "cohort"], how="left")
    total_by_context["cell_fraction"] = total_by_context["n_cells"] / total_by_context["total_cells"].replace(0, np.nan)

    for include_blasst in [False, True]:
        cohorts = REPORT_COHORTS if include_blasst else REPORT_COHORTS_NO_BLASST
        for (prep_root, panel), sub in total_by_context.groupby(["prep_root", "panel"], dropna=False):
            sub = sub[sub["cohort"].isin(cohorts)].copy()
            if sub.empty:
                continue
            top = sub.groupby("label")["n_cells"].sum().sort_values(ascending=False).head(top_n).index
            sub = sub[sub["label"].isin(top)].copy()
            mat = sub.pivot_table(index="label", columns="cohort", values="cell_fraction", aggfunc="sum", fill_value=0)
            mat = mat.reindex(columns=cohorts).fillna(0)
            mat = mat.loc[mat.sum(axis=1).sort_values(ascending=False).index]
            suffix = "withBLASST" if include_blasst else "noBLASST"
            stem = out_dir / f"{prefix}_{safe_filename(prep_root)}_{panel}_label_proportion_heatmap_{suffix}"
            out = plot_heatmap_matrix(
                mat,
                title=f"{prep_root} — {panel}: final label proportions ({suffix})",
                out_prefix=stem,
                value_label="Fraction of cells within cohort/panel",
                cmap="viridis",
            )
            if out:
                outputs.append(out)
    return outputs


def plot_marker_combo_heatmaps(
    marker_summary: pd.DataFrame,
    out_dir: Path,
    prefix: str,
    top_n: int = 40,
):
    outputs = []
    if marker_summary.empty:
        return outputs

    marker_summary = marker_summary.copy()
    marker_summary["row_label"] = marker_summary["marker_combo"].astype(str) + " → " + marker_summary["collapse_label"].astype(str)
    agg = (
        marker_summary.groupby(["panel", "cohort", "row_label", "excluded_from_primary"], dropna=False)["n_cells"]
        .sum()
        .reset_index()
    )
    totals = agg.groupby(["panel", "cohort"], dropna=False)["n_cells"].sum().reset_index(name="total_cells")
    agg = agg.merge(totals, on=["panel", "cohort"], how="left")
    agg["cell_fraction"] = agg["n_cells"] / agg["total_cells"].replace(0, np.nan)

    for include_blasst in [False, True]:
        cohorts = REPORT_COHORTS if include_blasst else REPORT_COHORTS_NO_BLASST
        for panel, sub in agg.groupby("panel", dropna=False):
            if panel not in PANEL_ORDER:
                continue
            sub = sub[sub["cohort"].isin(cohorts)].copy()
            if sub.empty:
                continue
            top = sub.groupby("row_label")["n_cells"].sum().sort_values(ascending=False).head(top_n).index
            sub = sub[sub["row_label"].isin(top)].copy()
            mat = sub.pivot_table(index="row_label", columns="cohort", values="cell_fraction", aggfunc="sum", fill_value=0)
            mat = mat.reindex(columns=cohorts).fillna(0)
            mat = mat.loc[mat.sum(axis=1).sort_values(ascending=False).index]
            suffix = "withBLASST" if include_blasst else "noBLASST"
            stem = out_dir / f"{prefix}_{panel}_marker_combo_proportion_heatmap_{suffix}"
            out = plot_heatmap_matrix(
                mat,
                title=f"{panel}: marker-combination proportions ({suffix})",
                out_prefix=stem,
                value_label="Fraction of cells within cohort/panel",
                cmap="magma",
            )
            if out:
                outputs.append(out)
    return outputs


# -----------------------------------------------------------------------------
# Main build function
# -----------------------------------------------------------------------------

def build_all_outputs(
    weibull_root: Path = DEFAULT_WEIBULL_ROOT,
    qc_dir: Path = DEFAULT_QC_DIR,
    cell_dir: Path = DEFAULT_CELL_DIR,
    out_dir: Path = DEFAULT_OUT_DIR,
    cohorts: list[str] | None = None,
    keep_qc_statuses: list[str] | None = None,
    require_all_primary_inputs: bool = True,
    top_n_heatmap: int = 40,
    max_stacked_labels: int = 25,
) -> dict:
    cohorts = cohorts or REPORT_COHORTS
    out_dir = Path(out_dir)
    plot_dir = out_dir / "plots"
    table_dir = out_dir / "tables"
    plot_dir.mkdir(parents=True, exist_ok=True)
    table_dir.mkdir(parents=True, exist_ok=True)

    valid_units = load_valid_units(
        qc_dir=qc_dir,
        cohorts=cohorts,
        panels=PANEL_ORDER,
        keep_qc_statuses=keep_qc_statuses,
        require_all_primary_inputs=require_all_primary_inputs,
    )
    valid_summary = make_valid_unit_summary(valid_units)
    valid_summary.to_csv(table_dir / "supp_table_valid_units_used_for_prep_root_audit.csv", index=False)

    counts = load_all_prep_counts(weibull_root=weibull_root, valid_units=valid_units)
    counts.to_csv(table_dir / "source_data_prep_root_unit_region_label_counts.csv", index=False)

    label_summary = make_label_summary(counts)
    label_summary.to_csv(table_dir / "supp_table_prep_root_label_summary.csv", index=False)

    label_by_cohort = make_label_by_cohort_summary(counts)
    label_by_cohort.to_csv(table_dir / "supp_table_prep_root_label_by_cohort_sample_type.csv", index=False)

    comp_summary = make_mean_composition_summary(counts)
    comp_summary.to_csv(table_dir / "supp_table_mean_cell_count_composition_by_region.csv", index=False)

    marker_summary = load_cell_df_counts(cell_dir=cell_dir, valid_units=valid_units, include_whole=True)
    if not marker_summary.empty:
        marker_summary.to_csv(table_dir / "supp_table_marker_combination_by_cohort.csv", index=False)

    # Prep-root inventory table.
    inv = []
    for root_name, root in prep_root_paths(weibull_root).items():
        files = list(iter_1nn_files(root)) if root.exists() else []
        inv.append({
            "prep_root": root_name,
            "path": str(root),
            "exists": root.exists(),
            "n_1NN_prep_files": len(files),
            "chunk_summary_exists": (root / "chunk_summary.tsv").exists(),
        })
    pd.DataFrame(inv).to_csv(table_dir / "supp_table_prep_root_inventory.csv", index=False)

    outputs = {
        "valid_units": valid_summary,
        "counts": counts,
        "label_summary": label_summary,
        "label_by_cohort": label_by_cohort,
        "composition_summary": comp_summary,
        "marker_summary": marker_summary,
        "plot_paths": [],
        "table_dir": table_dir,
        "plot_dir": plot_dir,
    }

    # Mean cell-count composition stacked bars.
    for prep_root in sorted(comp_summary["prep_root"].dropna().unique()):
        for panel in PANEL_ORDER:
            p = plot_mean_cell_count_composition(
                comp_summary,
                prep_root=prep_root,
                panel=panel,
                out_dir=plot_dir,
                cohorts=cohorts,
                prefix="report",
                max_stacked_labels=max_stacked_labels,
            )
            if p:
                outputs["plot_paths"].append(str(p))

    # Abundance vs consistency bubble plots: every prep root/panel, with and without BLASST.
    for prep_root in sorted(counts["prep_root"].dropna().unique()):
        for panel in PANEL_ORDER:
            for include_blasst in [False, True]:
                p = plot_abundance_consistency(
                    label_summary=label_summary,
                    prep_root=prep_root,
                    panel=panel,
                    out_dir=plot_dir,
                    include_blasst=include_blasst,
                    counts=counts,
                    prefix="report",
                    annotate_top_n=30,
                )
                if p:
                    outputs["plot_paths"].append(str(p))

    # Heatmaps.
    outputs["plot_paths"].extend(plot_label_proportion_heatmaps(counts, plot_dir, prefix="report", top_n=top_n_heatmap))
    outputs["plot_paths"].extend(plot_marker_combo_heatmaps(marker_summary, plot_dir, prefix="report", top_n=top_n_heatmap))

    # Data dictionary.
    dictionary = pd.DataFrame([
        {"file": "supp_table_valid_units_used_for_prep_root_audit.csv", "description": "QC/source-complete TMA cores and BLASST whole-section regions retained for report prep-root audits."},
        {"file": "source_data_prep_root_unit_region_label_counts.csv", "description": "Aggregated source data from 1NN_prep.tsv: one row per prep root/panel/cohort/unit/region/final label."},
        {"file": "supp_table_prep_root_label_summary.csv", "description": "Across-cohort abundance and consistency for each final prep-root label."},
        {"file": "supp_table_prep_root_label_by_cohort_sample_type.csv", "description": "Cell-count and cell-fraction summaries for each final label by cohort and sample type."},
        {"file": "supp_table_mean_cell_count_composition_by_region.csv", "description": "Mean cells per unit for each prep-root label in epithelial/tumor and stroma regions."},
        {"file": "supp_table_marker_combination_by_cohort.csv", "description": "Raw marker-combination/collapse-label cell fractions by cohort, sample type, and panel."},
        {"file": "supp_table_prep_root_inventory.csv", "description": "Discovered prep roots and number of 1NN_prep.tsv chunks."},
    ])
    dictionary.to_csv(table_dir / "prep_root_audit_table_dictionary.csv", index=False)

    print("\n[DONE] Prep-root label audit outputs")
    print(f"  Tables: {table_dir}")
    print(f"  Plots:  {plot_dir}")
    print(f"  n plots: {len(outputs['plot_paths'])}")
    return outputs


# -----------------------------------------------------------------------------
# CLI
# -----------------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser(description="Create DOD-report prep-root label audit plots and supplementary tables.")
    ap.add_argument("--weibull-root", default=str(DEFAULT_WEIBULL_ROOT))
    ap.add_argument("--qc-dir", default=str(DEFAULT_QC_DIR))
    ap.add_argument("--cell-dir", default=str(DEFAULT_CELL_DIR))
    ap.add_argument("--out-dir", default=str(DEFAULT_OUT_DIR))
    ap.add_argument("--cohorts", nargs="+", default=REPORT_COHORTS)
    ap.add_argument("--keep-qc-statuses", nargs="+", default=["Acceptable", "Borderline"])
    ap.add_argument("--no-require-all-primary-inputs", action="store_true")
    ap.add_argument("--top-n-heatmap", type=int, default=40)
    ap.add_argument("--max-stacked-labels", type=int, default=25)
    args = ap.parse_args()

    build_all_outputs(
        weibull_root=Path(args.weibull_root),
        qc_dir=Path(args.qc_dir),
        cell_dir=Path(args.cell_dir),
        out_dir=Path(args.out_dir),
        cohorts=args.cohorts,
        keep_qc_statuses=args.keep_qc_statuses,
        require_all_primary_inputs=not args.no_require_all_primary_inputs,
        top_n_heatmap=args.top_n_heatmap,
        max_stacked_labels=args.max_stacked_labels,
    )


if __name__ == "__main__":
    main()
